theme: minimal-mistakes-jekyll

locale: "zh-CN"


title: "Tonfeiz's blog"
name: "Tonfeiz"
url: "https://tonfeiz.github.io"
repository: "tonfeiz/tonfeiz.github.io"

author:
    name    : "tonfeiz"
    avatar  : ""
    bio     : ""
    location: "China"

